const membersData = [
    {
        dpNumber: "1000",
        username: "Joe",
        phoneNumber: "+91 8866889933",
        emailId: "joe@gmail.com",
        verify: "verified",
        verified: true,
        nonverified: false,
    },
    {
        dpNumber: "1001",
        username: "Jason",
        phoneNumber: "+91 9929220022",
        emailId: "jason@gmail.com",
        verify: "non-verified",
        verified: false,
        nonverified: true,
    },
    {
        dpNumber: "1002",
        username: "Steve",
        phoneNumber: "+91 7828338800",
        emailId: "steve@gmail.com",
        verify: "non-verified",
        verified: false,
        nonverified: true,
    },
    {
        dpNumber: "1003",
        username: "Mark",
        phoneNumber: "+91 9866003377",
        emailId: "mark@gmail.com",
        verify: "verified",
        verified: true,
        nonverified: false,
    },
    {
        dpNumber: "1004",
        username: "llyod",
        phoneNumber: "+91 8988775544",
        emailId: "llyod@gmail.com",
        verify: "non-verified",
        verified: false,
        nonverified: true,
    },
    {
        dpNumber: "1005",
        username: "philip",
        phoneNumber: "+91 7788665544",
        emailId: "philip@gmail.com",
        verify: "verified",
        verified: true,
        nonverified: false,
    },
    {
        dpNumber: "1006",
        username: "carin",
        phoneNumber: "+91 6677668855",
        emailId: "carin@gmail.com",
        verify: "verified",
        verified: true,
        nonverified: false,
    },
    {
        dpNumber: "1007",
        username: "Fransis",
        phoneNumber: "+91 8756456789",
        emailId: "fransis@gmail.com",
        verify: "verified",
        verified: true,
        nonverified: false,
    },
    {
        dpNumber: "1008",
        username: "San",
        phoneNumber: "+91 7554355445",
        emailId: "san@gmail.com",
        verify: "verified",
        verified: true,
        nonverified: false,
    },
    {
        dpNumber: "1009",
        username: "John",
        phoneNumber: "+91 8866556644",
        emailId: "john@gmail.com",
        verify: "verified",
        verified: true,
        nonverified: false,
    },
    {
        dpNumber: "1010",
        username: "Henry",
        phoneNumber: "+91 8977667755",
        emailId: "henry@gmail.com",
        verify: "non-verified",
        verified: false,
        nonverified: true,
    },
  ];

  export default membersData;