const membersData = [
    {
        dpNumber: "1000",
        username: "Joe",
        phoneNumber: "+918866889933",
        emailId: "joe@gmail.com",
        verify: "verified",
        verified: true,
    },
    {
        dpNumber: "1001",
        username: "Jason",
        phoneNumber: "+919929220022",
        emailId: "jason@gmail.com",
        verify: "non-verified",
        verified: false,
    },
    {
        dpNumber: "1002",
        username: "Steve",
        phoneNumber: "+917828338800",
        emailId: "steve@gmail.com",
        verify: "non-verified",
        verified: false,
    },
    {
        dpNumber: "1003",
        username: "Mark",
        phoneNumber: "+919866003377",
        emailId: "mark@gmail.com",
        verify: "verified",
        verified: true,
    },
    {
        dpNumber: "1004",
        username: "llyod",
        phoneNumber: "+918988775544",
        emailId: "llyod@gmail.com",
        verify: "non-verified",
        verified: false,
    },
    {
        dpNumber: "1005",
        username: "philip",
        phoneNumber: "+917788665544",
        emailId: "philip@gmail.com",
        verify: "verified",
        verified: true,
    },
    {
        dpNumber: "1006",
        username: "carin",
        phoneNumber: "+916677668855",
        emailId: "carin@gmail.com",
        verify: "verified",
        verified: true,
    },
    {
        dpNumber: "1007",
        username: "Fransis",
        phoneNumber: "+918756456789",
        emailId: "fransis@gmail.com",
        verify: "verified",
        verified: true,
    },
    {
        dpNumber: "1008",
        username: "San",
        phoneNumber: "+917554355445",
        emailId: "san@gmail.com",
        verify: "verified",
        verified: true,
    },
    {
        dpNumber: "1009",
        username: "John",
        phoneNumber: "+918866556644",
        emailId: "john@gmail.com",
        verify: "verified",
        verified: true,
    },
    {
        dpNumber: "1010",
        username: "Henry",
        phoneNumber: "+918977667755",
        emailId: "henry@gmail.com",
        verify: "non-verified",
        verified: false,
    },
  ];

  export default membersData;